# Start with a base Debian image
FROM debian:bookworm-slim

# Set environment variables to non-interactive (this prevents some prompts)
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install necessary dependencies for building Python packages and zsh
# require root access
RUN apt-get update && \
    apt-get install -y \
    python3.11 \
    python3.11-dev \
    python3-pip \
    python3-venv \  
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    zsh \
    curl \
    git \
    autojump && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set Python 3.11 as the default Python version: requires root
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

# install sudo so we can create a non root account to use as default
RUN apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

# Switch to non-root user
USER $USERNAME

# Create the virtual environment, activate it, and install packages
RUN python3 -m venv /home/user/c3 && \
    . /home/user/c3/bin/activate && \
    pip install --upgrade pip && \
    pip install "cogent3[extra]" flit jupyter ipykernel unsync click

# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Set zsh as the default shell
SHELL ["/usr/bin/zsh", "-c"]

# Create a default .zshrc file with some suggested configurations
RUN echo 'export ZSH="$HOME/.oh-my-zsh"' >> $HOME/.zshrc && \
    echo 'ZSH_THEME="robbyrussell"' >> $HOME/.zshrc && \
    echo 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting autojump)' >> $HOME/.zshrc && \
    echo 'source $ZSH/oh-my-zsh.sh' >> $HOME/.zshrc && \
    echo 'export HISTFILE=~/.zsh_history' >> $HOME/.zshrc && \
    echo 'export HISTSIZE=10000' >> $HOME/.zshrc && \
    echo 'export SAVEHIST=10000' >> $HOME/.zshrc && \
    echo 'setopt appendhistory' >> $HOME/.zshrc && \
    echo 'setopt histignorespace' >> $HOME/.zshrc && \
    echo 'setopt histignorealldups' >> $HOME/.zshrc && \
    echo 'source /home/user/c3/bin/activate' >> $HOME/.zshrc

# Install zsh-autosuggestions and zsh-syntax-highlighting plugins
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Add venv to bash and zsh shells
RUN echo 'source /home/user/c3/bin/activate' >> /home/user/.bashrc && \
    echo 'source /home/user/c3/bin/activate' >> /home/user/.zshrc

# Set up a working directory
WORKDIR /workspace/Cogent3Workshop

# Start a terminal session using the zsh shell
CMD ["/usr/bin/zsh"] 